# Generated by Django 5.1.4 on 2024-12-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.FloatField()),
                ('category', models.CharField(choices=[('HB', 'Hot-Beverages'), ('CB', 'Cold-Beverages'), ('RF', 'Refreshment'), ('SC', 'Special-Combos'), ('DE', 'Dessert'), ('BF', 'Burger-&-FrenchFries')], max_length=2)),
            ],
        ),
    ]
